AWSTemplateFormatVerion '2010-09-09'
Transform 'AWS::Serverless-2016-10-31'
Resources:
  GetAvFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.get
      Runtime: nodejs6.10
      CodeUri: